/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DropRouteImport } from './routes/drop'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as AppWrappedRouteImport } from './routes/app.wrapped'
import { Route as AppTopRouteImport } from './routes/app.top'
import { Route as AppSquadRouteImport } from './routes/app.squad'
import { Route as AppSpritzIndexRouteImport } from './routes/app.spritz-index'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppReplayRouteImport } from './routes/app.replay'
import { Route as AppReelsRouteImport } from './routes/app.reels'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppPartiesRouteImport } from './routes/app.parties'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppLastcallsRouteImport } from './routes/app.lastcalls'
import { Route as AppInviteRouteImport } from './routes/app.invite'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppFollowersRouteImport } from './routes/app.followers'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppFazeRouteImport } from './routes/app.faze'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppBlockedRouteImport } from './routes/app.blocked'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known.assetlinks[.]json'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known.apple-app-site-association'
import { Route as AppBizIndexRouteImport } from './routes/app.biz.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppVenueIdRouteImport } from './routes/app.venue.$id'
import { Route as AppUserIdRouteImport } from './routes/app.user.$id'
import { Route as AppStreetIdRouteImport } from './routes/app.street.$id'
import { Route as AppReplayDateRouteImport } from './routes/app.replay.$date'
import { Route as AppPromoIdRouteImport } from './routes/app.promo.$id'
import { Route as AppPhotoIdRouteImport } from './routes/app.photo.$id'
import { Route as AppMeReputationRouteImport } from './routes/app.me_.reputation'
import { Route as AppMeRatersRouteImport } from './routes/app.me_.raters'
import { Route as AppMeArchiveRouteImport } from './routes/app.me_.archive'
import { Route as AppCitySlugRouteImport } from './routes/app.city.$slug'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as AppBizExclusiveRouteImport } from './routes/app.biz.exclusive'
import { Route as AppBizDashboardRouteImport } from './routes/app.biz.dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminPlacesRouteImport } from './routes/app.admin.places'
import { Route as AppAdminDebugRouteImport } from './routes/app.admin.debug'
import { Route as AppAdminContentRouteImport } from './routes/app.admin.content'
import { Route as AppAdminCampaignsRouteImport } from './routes/app.admin.campaigns'
import { Route as AppAdminBusinessesRouteImport } from './routes/app.admin.businesses'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronStreakRiskRouteImport } from './routes/api/public/cron.streak-risk'
import { Route as ApiPublicCronHeatAlertsRouteImport } from './routes/api/public/cron.heat-alerts'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DropRoute = DropRouteImport.update({
  id: '/drop',
  path: '/drop',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWrappedRoute = AppWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)
const AppTopRoute = AppTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => AppRoute,
} as any)
const AppSquadRoute = AppSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AppRoute,
} as any)
const AppSpritzIndexRoute = AppSpritzIndexRouteImport.update({
  id: '/spritz-index',
  path: '/spritz-index',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppLastcallsRoute = AppLastcallsRouteImport.update({
  id: '/lastcalls',
  path: '/lastcalls',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowersRoute = AppFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppFazeRoute = AppFazeRouteImport.update({
  id: '/faze',
  path: '/faze',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppBlockedRoute = AppBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppBizIndexRoute = AppBizIndexRouteImport.update({
  id: '/biz/',
  path: '/biz/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVenueIdRoute = AppVenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUserIdRoute = AppUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStreetIdRoute = AppStreetIdRouteImport.update({
  id: '/street/$id',
  path: '/street/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayDateRoute = AppReplayDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => AppReplayRoute,
} as any)
const AppPromoIdRoute = AppPromoIdRouteImport.update({
  id: '/promo/$id',
  path: '/promo/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotoIdRoute = AppPhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMeReputationRoute = AppMeReputationRouteImport.update({
  id: '/me_/reputation',
  path: '/me/reputation',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRatersRoute = AppMeRatersRouteImport.update({
  id: '/me_/raters',
  path: '/me/raters',
  getParentRoute: () => AppRoute,
} as any)
const AppMeArchiveRoute = AppMeArchiveRouteImport.update({
  id: '/me_/archive',
  path: '/me/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppCitySlugRoute = AppCitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBizExclusiveRoute = AppBizExclusiveRouteImport.update({
  id: '/biz/exclusive',
  path: '/biz/exclusive',
  getParentRoute: () => AppRoute,
} as any)
const AppBizDashboardRoute = AppBizDashboardRouteImport.update({
  id: '/biz/dashboard',
  path: '/biz/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlacesRoute = AppAdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDebugRoute = AppAdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCampaignsRoute = AppAdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBusinessesRoute = AppAdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronStreakRiskRoute = ApiPublicCronStreakRiskRouteImport.update({
  id: '/api/public/cron/streak-risk',
  path: '/api/public/cron/streak-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronHeatAlertsRoute = ApiPublicCronHeatAlertsRouteImport.update({
  id: '/api/public/cron/heat-alerts',
  path: '/api/public/cron/heat-alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/drop': typeof DropRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/blocked': typeof AppBlockedRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/faze': typeof AppFazeRoute
  '/app/feed': typeof AppFeedRoute
  '/app/followers': typeof AppFollowersRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invite': typeof AppInviteRoute
  '/app/lastcalls': typeof AppLastcallsRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/reels': typeof AppReelsRoute
  '/app/replay': typeof AppReplayRouteWithChildren
  '/app/requests': typeof AppRequestsRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/spritz-index': typeof AppSpritzIndexRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/wrapped': typeof AppWrappedRoute
  '/u/$handle': typeof UHandleRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/businesses': typeof AppAdminBusinessesRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/debug': typeof AppAdminDebugRoute
  '/app/admin/places': typeof AppAdminPlacesRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/biz/dashboard': typeof AppBizDashboardRoute
  '/app/biz/exclusive': typeof AppBizExclusiveRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/me/archive': typeof AppMeArchiveRoute
  '/app/me/raters': typeof AppMeRatersRoute
  '/app/me/reputation': typeof AppMeReputationRoute
  '/app/photo/$id': typeof AppPhotoIdRoute
  '/app/promo/$id': typeof AppPromoIdRoute
  '/app/replay/$date': typeof AppReplayDateRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/biz/': typeof AppBizIndexRoute
  '/api/public/cron/heat-alerts': typeof ApiPublicCronHeatAlertsRoute
  '/api/public/cron/streak-risk': typeof ApiPublicCronStreakRiskRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/drop': typeof DropRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/faze': typeof AppFazeRoute
  '/app/feed': typeof AppFeedRoute
  '/app/followers': typeof AppFollowersRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invite': typeof AppInviteRoute
  '/app/lastcalls': typeof AppLastcallsRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/reels': typeof AppReelsRoute
  '/app/replay': typeof AppReplayRouteWithChildren
  '/app/requests': typeof AppRequestsRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/spritz-index': typeof AppSpritzIndexRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/wrapped': typeof AppWrappedRoute
  '/u/$handle': typeof UHandleRoute
  '/app': typeof AppIndexRoute
  '/app/admin/businesses': typeof AppAdminBusinessesRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/debug': typeof AppAdminDebugRoute
  '/app/admin/places': typeof AppAdminPlacesRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/biz/dashboard': typeof AppBizDashboardRoute
  '/app/biz/exclusive': typeof AppBizExclusiveRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/me/archive': typeof AppMeArchiveRoute
  '/app/me/raters': typeof AppMeRatersRoute
  '/app/me/reputation': typeof AppMeReputationRoute
  '/app/photo/$id': typeof AppPhotoIdRoute
  '/app/promo/$id': typeof AppPromoIdRoute
  '/app/replay/$date': typeof AppReplayDateRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/biz': typeof AppBizIndexRoute
  '/api/public/cron/heat-alerts': typeof ApiPublicCronHeatAlertsRoute
  '/api/public/cron/streak-risk': typeof ApiPublicCronStreakRiskRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/drop': typeof DropRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/blocked': typeof AppBlockedRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/faze': typeof AppFazeRoute
  '/app/feed': typeof AppFeedRoute
  '/app/followers': typeof AppFollowersRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invite': typeof AppInviteRoute
  '/app/lastcalls': typeof AppLastcallsRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/reels': typeof AppReelsRoute
  '/app/replay': typeof AppReplayRouteWithChildren
  '/app/requests': typeof AppRequestsRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/spritz-index': typeof AppSpritzIndexRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/wrapped': typeof AppWrappedRoute
  '/u/$handle': typeof UHandleRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/businesses': typeof AppAdminBusinessesRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/debug': typeof AppAdminDebugRoute
  '/app/admin/places': typeof AppAdminPlacesRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/biz/dashboard': typeof AppBizDashboardRoute
  '/app/biz/exclusive': typeof AppBizExclusiveRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/me_/archive': typeof AppMeArchiveRoute
  '/app/me_/raters': typeof AppMeRatersRoute
  '/app/me_/reputation': typeof AppMeReputationRoute
  '/app/photo/$id': typeof AppPhotoIdRoute
  '/app/promo/$id': typeof AppPromoIdRoute
  '/app/replay/$date': typeof AppReplayDateRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/biz/': typeof AppBizIndexRoute
  '/api/public/cron/heat-alerts': typeof ApiPublicCronHeatAlertsRoute
  '/api/public/cron/streak-risk': typeof ApiPublicCronStreakRiskRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cookies'
    | '/drop'
    | '/forgot-password'
    | '/hall-of-fame'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/app/admin'
    | '/app/blocked'
    | '/app/discover'
    | '/app/faze'
    | '/app/feed'
    | '/app/followers'
    | '/app/friends'
    | '/app/inbox'
    | '/app/invite'
    | '/app/lastcalls'
    | '/app/map'
    | '/app/me'
    | '/app/notifications'
    | '/app/parties'
    | '/app/premium'
    | '/app/reels'
    | '/app/replay'
    | '/app/requests'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/spritz-index'
    | '/app/squad'
    | '/app/top'
    | '/app/wrapped'
    | '/u/$handle'
    | '/app/'
    | '/app/admin/businesses'
    | '/app/admin/campaigns'
    | '/app/admin/content'
    | '/app/admin/debug'
    | '/app/admin/places'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/biz/dashboard'
    | '/app/biz/exclusive'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/me/archive'
    | '/app/me/raters'
    | '/app/me/reputation'
    | '/app/photo/$id'
    | '/app/promo/$id'
    | '/app/replay/$date'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
    | '/app/admin/'
    | '/app/biz/'
    | '/api/public/cron/heat-alerts'
    | '/api/public/cron/streak-risk'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/drop'
    | '/forgot-password'
    | '/hall-of-fame'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/app/blocked'
    | '/app/discover'
    | '/app/faze'
    | '/app/feed'
    | '/app/followers'
    | '/app/friends'
    | '/app/inbox'
    | '/app/invite'
    | '/app/lastcalls'
    | '/app/map'
    | '/app/me'
    | '/app/notifications'
    | '/app/parties'
    | '/app/premium'
    | '/app/reels'
    | '/app/replay'
    | '/app/requests'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/spritz-index'
    | '/app/squad'
    | '/app/top'
    | '/app/wrapped'
    | '/u/$handle'
    | '/app'
    | '/app/admin/businesses'
    | '/app/admin/campaigns'
    | '/app/admin/content'
    | '/app/admin/debug'
    | '/app/admin/places'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/biz/dashboard'
    | '/app/biz/exclusive'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/me/archive'
    | '/app/me/raters'
    | '/app/me/reputation'
    | '/app/photo/$id'
    | '/app/promo/$id'
    | '/app/replay/$date'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
    | '/app/admin'
    | '/app/biz'
    | '/api/public/cron/heat-alerts'
    | '/api/public/cron/streak-risk'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cookies'
    | '/drop'
    | '/forgot-password'
    | '/hall-of-fame'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/app/admin'
    | '/app/blocked'
    | '/app/discover'
    | '/app/faze'
    | '/app/feed'
    | '/app/followers'
    | '/app/friends'
    | '/app/inbox'
    | '/app/invite'
    | '/app/lastcalls'
    | '/app/map'
    | '/app/me'
    | '/app/notifications'
    | '/app/parties'
    | '/app/premium'
    | '/app/reels'
    | '/app/replay'
    | '/app/requests'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/spritz-index'
    | '/app/squad'
    | '/app/top'
    | '/app/wrapped'
    | '/u/$handle'
    | '/app/'
    | '/app/admin/businesses'
    | '/app/admin/campaigns'
    | '/app/admin/content'
    | '/app/admin/debug'
    | '/app/admin/places'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/biz/dashboard'
    | '/app/biz/exclusive'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/me_/archive'
    | '/app/me_/raters'
    | '/app/me_/reputation'
    | '/app/photo/$id'
    | '/app/promo/$id'
    | '/app/replay/$date'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
    | '/app/admin/'
    | '/app/biz/'
    | '/api/public/cron/heat-alerts'
    | '/api/public/cron/streak-risk'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DropRoute: typeof DropRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HallOfFameRoute: typeof HallOfFameRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  UHandleRoute: typeof UHandleRoute
  ApiPublicCronHeatAlertsRoute: typeof ApiPublicCronHeatAlertsRoute
  ApiPublicCronStreakRiskRoute: typeof ApiPublicCronStreakRiskRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop': {
      id: '/drop'
      path: '/drop'
      fullPath: '/drop'
      preLoaderRoute: typeof DropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wrapped': {
      id: '/app/wrapped'
      path: '/wrapped'
      fullPath: '/app/wrapped'
      preLoaderRoute: typeof AppWrappedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/top': {
      id: '/app/top'
      path: '/top'
      fullPath: '/app/top'
      preLoaderRoute: typeof AppTopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/squad': {
      id: '/app/squad'
      path: '/squad'
      fullPath: '/app/squad'
      preLoaderRoute: typeof AppSquadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spritz-index': {
      id: '/app/spritz-index'
      path: '/spritz-index'
      fullPath: '/app/spritz-index'
      preLoaderRoute: typeof AppSpritzIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/replay': {
      id: '/app/replay'
      path: '/replay'
      fullPath: '/app/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reels': {
      id: '/app/reels'
      path: '/reels'
      fullPath: '/app/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parties': {
      id: '/app/parties'
      path: '/parties'
      fullPath: '/app/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lastcalls': {
      id: '/app/lastcalls'
      path: '/lastcalls'
      fullPath: '/app/lastcalls'
      preLoaderRoute: typeof AppLastcallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invite': {
      id: '/app/invite'
      path: '/invite'
      fullPath: '/app/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/followers': {
      id: '/app/followers'
      path: '/followers'
      fullPath: '/app/followers'
      preLoaderRoute: typeof AppFollowersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faze': {
      id: '/app/faze'
      path: '/faze'
      fullPath: '/app/faze'
      preLoaderRoute: typeof AppFazeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blocked': {
      id: '/app/blocked'
      path: '/blocked'
      fullPath: '/app/blocked'
      preLoaderRoute: typeof AppBlockedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/biz/': {
      id: '/app/biz/'
      path: '/biz'
      fullPath: '/app/biz/'
      preLoaderRoute: typeof AppBizIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/venue/$id': {
      id: '/app/venue/$id'
      path: '/venue/$id'
      fullPath: '/app/venue/$id'
      preLoaderRoute: typeof AppVenueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user/$id': {
      id: '/app/user/$id'
      path: '/user/$id'
      fullPath: '/app/user/$id'
      preLoaderRoute: typeof AppUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/street/$id': {
      id: '/app/street/$id'
      path: '/street/$id'
      fullPath: '/app/street/$id'
      preLoaderRoute: typeof AppStreetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/replay/$date': {
      id: '/app/replay/$date'
      path: '/$date'
      fullPath: '/app/replay/$date'
      preLoaderRoute: typeof AppReplayDateRouteImport
      parentRoute: typeof AppReplayRoute
    }
    '/app/promo/$id': {
      id: '/app/promo/$id'
      path: '/promo/$id'
      fullPath: '/app/promo/$id'
      preLoaderRoute: typeof AppPromoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/photo/$id': {
      id: '/app/photo/$id'
      path: '/photo/$id'
      fullPath: '/app/photo/$id'
      preLoaderRoute: typeof AppPhotoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me_/reputation': {
      id: '/app/me_/reputation'
      path: '/me/reputation'
      fullPath: '/app/me/reputation'
      preLoaderRoute: typeof AppMeReputationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me_/raters': {
      id: '/app/me_/raters'
      path: '/me/raters'
      fullPath: '/app/me/raters'
      preLoaderRoute: typeof AppMeRatersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me_/archive': {
      id: '/app/me_/archive'
      path: '/me/archive'
      fullPath: '/app/me/archive'
      preLoaderRoute: typeof AppMeArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/city/$slug': {
      id: '/app/city/$slug'
      path: '/city/$slug'
      fullPath: '/app/city/$slug'
      preLoaderRoute: typeof AppCitySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biz/exclusive': {
      id: '/app/biz/exclusive'
      path: '/biz/exclusive'
      fullPath: '/app/biz/exclusive'
      preLoaderRoute: typeof AppBizExclusiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biz/dashboard': {
      id: '/app/biz/dashboard'
      path: '/biz/dashboard'
      fullPath: '/app/biz/dashboard'
      preLoaderRoute: typeof AppBizDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/places': {
      id: '/app/admin/places'
      path: '/places'
      fullPath: '/app/admin/places'
      preLoaderRoute: typeof AppAdminPlacesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/debug': {
      id: '/app/admin/debug'
      path: '/debug'
      fullPath: '/app/admin/debug'
      preLoaderRoute: typeof AppAdminDebugRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/content': {
      id: '/app/admin/content'
      path: '/content'
      fullPath: '/app/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/campaigns': {
      id: '/app/admin/campaigns'
      path: '/campaigns'
      fullPath: '/app/admin/campaigns'
      preLoaderRoute: typeof AppAdminCampaignsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/businesses': {
      id: '/app/admin/businesses'
      path: '/businesses'
      fullPath: '/app/admin/businesses'
      preLoaderRoute: typeof AppAdminBusinessesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/streak-risk': {
      id: '/api/public/cron/streak-risk'
      path: '/api/public/cron/streak-risk'
      fullPath: '/api/public/cron/streak-risk'
      preLoaderRoute: typeof ApiPublicCronStreakRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/heat-alerts': {
      id: '/api/public/cron/heat-alerts'
      path: '/api/public/cron/heat-alerts'
      fullPath: '/api/public/cron/heat-alerts'
      preLoaderRoute: typeof ApiPublicCronHeatAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBusinessesRoute: typeof AppAdminBusinessesRoute
  AppAdminCampaignsRoute: typeof AppAdminCampaignsRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminDebugRoute: typeof AppAdminDebugRoute
  AppAdminPlacesRoute: typeof AppAdminPlacesRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBusinessesRoute: AppAdminBusinessesRoute,
  AppAdminCampaignsRoute: AppAdminCampaignsRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminDebugRoute: AppAdminDebugRoute,
  AppAdminPlacesRoute: AppAdminPlacesRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppReplayRouteChildren {
  AppReplayDateRoute: typeof AppReplayDateRoute
}

const AppReplayRouteChildren: AppReplayRouteChildren = {
  AppReplayDateRoute: AppReplayDateRoute,
}

const AppReplayRouteWithChildren = AppReplayRoute._addFileChildren(
  AppReplayRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBlockedRoute: typeof AppBlockedRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFazeRoute: typeof AppFazeRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFollowersRoute: typeof AppFollowersRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInviteRoute: typeof AppInviteRoute
  AppLastcallsRoute: typeof AppLastcallsRoute
  AppMapRoute: typeof AppMapRoute
  AppMeRoute: typeof AppMeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppReelsRoute: typeof AppReelsRoute
  AppReplayRoute: typeof AppReplayRouteWithChildren
  AppRequestsRoute: typeof AppRequestsRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppSpritzIndexRoute: typeof AppSpritzIndexRoute
  AppSquadRoute: typeof AppSquadRoute
  AppTopRoute: typeof AppTopRoute
  AppWrappedRoute: typeof AppWrappedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBizDashboardRoute: typeof AppBizDashboardRoute
  AppBizExclusiveRoute: typeof AppBizExclusiveRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppCitySlugRoute: typeof AppCitySlugRoute
  AppMeArchiveRoute: typeof AppMeArchiveRoute
  AppMeRatersRoute: typeof AppMeRatersRoute
  AppMeReputationRoute: typeof AppMeReputationRoute
  AppPhotoIdRoute: typeof AppPhotoIdRoute
  AppPromoIdRoute: typeof AppPromoIdRoute
  AppStreetIdRoute: typeof AppStreetIdRoute
  AppUserIdRoute: typeof AppUserIdRoute
  AppVenueIdRoute: typeof AppVenueIdRoute
  AppBizIndexRoute: typeof AppBizIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBlockedRoute: AppBlockedRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFazeRoute: AppFazeRoute,
  AppFeedRoute: AppFeedRoute,
  AppFollowersRoute: AppFollowersRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppInboxRoute: AppInboxRoute,
  AppInviteRoute: AppInviteRoute,
  AppLastcallsRoute: AppLastcallsRoute,
  AppMapRoute: AppMapRoute,
  AppMeRoute: AppMeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppReelsRoute: AppReelsRoute,
  AppReplayRoute: AppReplayRouteWithChildren,
  AppRequestsRoute: AppRequestsRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppSpritzIndexRoute: AppSpritzIndexRoute,
  AppSquadRoute: AppSquadRoute,
  AppTopRoute: AppTopRoute,
  AppWrappedRoute: AppWrappedRoute,
  AppIndexRoute: AppIndexRoute,
  AppBizDashboardRoute: AppBizDashboardRoute,
  AppBizExclusiveRoute: AppBizExclusiveRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppCitySlugRoute: AppCitySlugRoute,
  AppMeArchiveRoute: AppMeArchiveRoute,
  AppMeRatersRoute: AppMeRatersRoute,
  AppMeReputationRoute: AppMeReputationRoute,
  AppPhotoIdRoute: AppPhotoIdRoute,
  AppPromoIdRoute: AppPromoIdRoute,
  AppStreetIdRoute: AppStreetIdRoute,
  AppUserIdRoute: AppUserIdRoute,
  AppVenueIdRoute: AppVenueIdRoute,
  AppBizIndexRoute: AppBizIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DropRoute: DropRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HallOfFameRoute: HallOfFameRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  UHandleRoute: UHandleRoute,
  ApiPublicCronHeatAlertsRoute: ApiPublicCronHeatAlertsRoute,
  ApiPublicCronStreakRiskRoute: ApiPublicCronStreakRiskRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
