/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTopRouteImport } from './routes/app.top'
import { Route as AppSquadRouteImport } from './routes/app.squad'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppPartiesRouteImport } from './routes/app.parties'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppFollowersRouteImport } from './routes/app.followers'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppFazeRouteImport } from './routes/app.faze'
import { Route as AppBlockedRouteImport } from './routes/app.blocked'
import { Route as AppBizRouteImport } from './routes/app.biz'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppVenueIdRouteImport } from './routes/app.venue.$id'
import { Route as AppUserIdRouteImport } from './routes/app.user.$id'
import { Route as AppStreetIdRouteImport } from './routes/app.street.$id'
import { Route as AppPromoIdRouteImport } from './routes/app.promo.$id'
import { Route as AppCitySlugRouteImport } from './routes/app.city.$slug'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminPlacesRouteImport } from './routes/app.admin.places'
import { Route as AppAdminContentRouteImport } from './routes/app.admin.content'
import { Route as AppAdminCampaignsRouteImport } from './routes/app.admin.campaigns'
import { Route as AppAdminBusinessesRouteImport } from './routes/app.admin.businesses'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopRoute = AppTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => AppRoute,
} as any)
const AppSquadRoute = AppSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowersRoute = AppFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppFazeRoute = AppFazeRouteImport.update({
  id: '/faze',
  path: '/faze',
  getParentRoute: () => AppRoute,
} as any)
const AppBlockedRoute = AppBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AppRoute,
} as any)
const AppBizRoute = AppBizRouteImport.update({
  id: '/biz',
  path: '/biz',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVenueIdRoute = AppVenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUserIdRoute = AppUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStreetIdRoute = AppStreetIdRouteImport.update({
  id: '/street/$id',
  path: '/street/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPromoIdRoute = AppPromoIdRouteImport.update({
  id: '/promo/$id',
  path: '/promo/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCitySlugRoute = AppCitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlacesRoute = AppAdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCampaignsRoute = AppAdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBusinessesRoute = AppAdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/biz': typeof AppBizRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/faze': typeof AppFazeRoute
  '/app/feed': typeof AppFeedRoute
  '/app/followers': typeof AppFollowersRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/businesses': typeof AppAdminBusinessesRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/places': typeof AppAdminPlacesRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/promo/$id': typeof AppPromoIdRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/biz': typeof AppBizRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/faze': typeof AppFazeRoute
  '/app/feed': typeof AppFeedRoute
  '/app/followers': typeof AppFollowersRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app': typeof AppIndexRoute
  '/app/admin/businesses': typeof AppAdminBusinessesRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/places': typeof AppAdminPlacesRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/promo/$id': typeof AppPromoIdRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/biz': typeof AppBizRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/faze': typeof AppFazeRoute
  '/app/feed': typeof AppFeedRoute
  '/app/followers': typeof AppFollowersRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/businesses': typeof AppAdminBusinessesRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/places': typeof AppAdminPlacesRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/promo/$id': typeof AppPromoIdRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/admin'
    | '/app/biz'
    | '/app/blocked'
    | '/app/faze'
    | '/app/feed'
    | '/app/followers'
    | '/app/friends'
    | '/app/inbox'
    | '/app/map'
    | '/app/me'
    | '/app/notifications'
    | '/app/parties'
    | '/app/premium'
    | '/app/requests'
    | '/app/scan'
    | '/app/settings'
    | '/app/squad'
    | '/app/top'
    | '/app/'
    | '/app/admin/businesses'
    | '/app/admin/campaigns'
    | '/app/admin/content'
    | '/app/admin/places'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/promo/$id'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/biz'
    | '/app/blocked'
    | '/app/faze'
    | '/app/feed'
    | '/app/followers'
    | '/app/friends'
    | '/app/inbox'
    | '/app/map'
    | '/app/me'
    | '/app/notifications'
    | '/app/parties'
    | '/app/premium'
    | '/app/requests'
    | '/app/scan'
    | '/app/settings'
    | '/app/squad'
    | '/app/top'
    | '/app'
    | '/app/admin/businesses'
    | '/app/admin/campaigns'
    | '/app/admin/content'
    | '/app/admin/places'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/promo/$id'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/admin'
    | '/app/biz'
    | '/app/blocked'
    | '/app/faze'
    | '/app/feed'
    | '/app/followers'
    | '/app/friends'
    | '/app/inbox'
    | '/app/map'
    | '/app/me'
    | '/app/notifications'
    | '/app/parties'
    | '/app/premium'
    | '/app/requests'
    | '/app/scan'
    | '/app/settings'
    | '/app/squad'
    | '/app/top'
    | '/app/'
    | '/app/admin/businesses'
    | '/app/admin/campaigns'
    | '/app/admin/content'
    | '/app/admin/places'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/promo/$id'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/top': {
      id: '/app/top'
      path: '/top'
      fullPath: '/app/top'
      preLoaderRoute: typeof AppTopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/squad': {
      id: '/app/squad'
      path: '/squad'
      fullPath: '/app/squad'
      preLoaderRoute: typeof AppSquadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parties': {
      id: '/app/parties'
      path: '/parties'
      fullPath: '/app/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/followers': {
      id: '/app/followers'
      path: '/followers'
      fullPath: '/app/followers'
      preLoaderRoute: typeof AppFollowersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faze': {
      id: '/app/faze'
      path: '/faze'
      fullPath: '/app/faze'
      preLoaderRoute: typeof AppFazeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blocked': {
      id: '/app/blocked'
      path: '/blocked'
      fullPath: '/app/blocked'
      preLoaderRoute: typeof AppBlockedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biz': {
      id: '/app/biz'
      path: '/biz'
      fullPath: '/app/biz'
      preLoaderRoute: typeof AppBizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/venue/$id': {
      id: '/app/venue/$id'
      path: '/venue/$id'
      fullPath: '/app/venue/$id'
      preLoaderRoute: typeof AppVenueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user/$id': {
      id: '/app/user/$id'
      path: '/user/$id'
      fullPath: '/app/user/$id'
      preLoaderRoute: typeof AppUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/street/$id': {
      id: '/app/street/$id'
      path: '/street/$id'
      fullPath: '/app/street/$id'
      preLoaderRoute: typeof AppStreetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promo/$id': {
      id: '/app/promo/$id'
      path: '/promo/$id'
      fullPath: '/app/promo/$id'
      preLoaderRoute: typeof AppPromoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/city/$slug': {
      id: '/app/city/$slug'
      path: '/city/$slug'
      fullPath: '/app/city/$slug'
      preLoaderRoute: typeof AppCitySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/places': {
      id: '/app/admin/places'
      path: '/places'
      fullPath: '/app/admin/places'
      preLoaderRoute: typeof AppAdminPlacesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/content': {
      id: '/app/admin/content'
      path: '/content'
      fullPath: '/app/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/campaigns': {
      id: '/app/admin/campaigns'
      path: '/campaigns'
      fullPath: '/app/admin/campaigns'
      preLoaderRoute: typeof AppAdminCampaignsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/businesses': {
      id: '/app/admin/businesses'
      path: '/businesses'
      fullPath: '/app/admin/businesses'
      preLoaderRoute: typeof AppAdminBusinessesRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBusinessesRoute: typeof AppAdminBusinessesRoute
  AppAdminCampaignsRoute: typeof AppAdminCampaignsRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminPlacesRoute: typeof AppAdminPlacesRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBusinessesRoute: AppAdminBusinessesRoute,
  AppAdminCampaignsRoute: AppAdminCampaignsRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminPlacesRoute: AppAdminPlacesRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBizRoute: typeof AppBizRoute
  AppBlockedRoute: typeof AppBlockedRoute
  AppFazeRoute: typeof AppFazeRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFollowersRoute: typeof AppFollowersRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMapRoute: typeof AppMapRoute
  AppMeRoute: typeof AppMeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSquadRoute: typeof AppSquadRoute
  AppTopRoute: typeof AppTopRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppCitySlugRoute: typeof AppCitySlugRoute
  AppPromoIdRoute: typeof AppPromoIdRoute
  AppStreetIdRoute: typeof AppStreetIdRoute
  AppUserIdRoute: typeof AppUserIdRoute
  AppVenueIdRoute: typeof AppVenueIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBizRoute: AppBizRoute,
  AppBlockedRoute: AppBlockedRoute,
  AppFazeRoute: AppFazeRoute,
  AppFeedRoute: AppFeedRoute,
  AppFollowersRoute: AppFollowersRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppInboxRoute: AppInboxRoute,
  AppMapRoute: AppMapRoute,
  AppMeRoute: AppMeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSquadRoute: AppSquadRoute,
  AppTopRoute: AppTopRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppCitySlugRoute: AppCitySlugRoute,
  AppPromoIdRoute: AppPromoIdRoute,
  AppStreetIdRoute: AppStreetIdRoute,
  AppUserIdRoute: AppUserIdRoute,
  AppVenueIdRoute: AppVenueIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
