/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTopRouteImport } from './routes/app.top'
import { Route as AppSquadRouteImport } from './routes/app.squad'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppPartiesRouteImport } from './routes/app.parties'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppFazeRouteImport } from './routes/app.faze'
import { Route as AppVenueIdRouteImport } from './routes/app.venue.$id'
import { Route as AppUserIdRouteImport } from './routes/app.user.$id'
import { Route as AppStreetIdRouteImport } from './routes/app.street.$id'
import { Route as AppCitySlugRouteImport } from './routes/app.city.$slug'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopRoute = AppTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => AppRoute,
} as any)
const AppSquadRoute = AppSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFazeRoute = AppFazeRouteImport.update({
  id: '/faze',
  path: '/faze',
  getParentRoute: () => AppRoute,
} as any)
const AppVenueIdRoute = AppVenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUserIdRoute = AppUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStreetIdRoute = AppStreetIdRouteImport.update({
  id: '/street/$id',
  path: '/street/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCitySlugRoute = AppCitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/faze': typeof AppFazeRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/scan': typeof AppScanRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/faze': typeof AppFazeRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/scan': typeof AppScanRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/faze': typeof AppFazeRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/map': typeof AppMapRoute
  '/app/me': typeof AppMeRoute
  '/app/parties': typeof AppPartiesRoute
  '/app/scan': typeof AppScanRoute
  '/app/squad': typeof AppSquadRoute
  '/app/top': typeof AppTopRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/city/$slug': typeof AppCitySlugRoute
  '/app/street/$id': typeof AppStreetIdRoute
  '/app/user/$id': typeof AppUserIdRoute
  '/app/venue/$id': typeof AppVenueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/faze'
    | '/app/friends'
    | '/app/inbox'
    | '/app/map'
    | '/app/me'
    | '/app/parties'
    | '/app/scan'
    | '/app/squad'
    | '/app/top'
    | '/app/'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/faze'
    | '/app/friends'
    | '/app/inbox'
    | '/app/map'
    | '/app/me'
    | '/app/parties'
    | '/app/scan'
    | '/app/squad'
    | '/app/top'
    | '/app'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/faze'
    | '/app/friends'
    | '/app/inbox'
    | '/app/map'
    | '/app/me'
    | '/app/parties'
    | '/app/scan'
    | '/app/squad'
    | '/app/top'
    | '/app/'
    | '/app/chat/$id'
    | '/app/city/$slug'
    | '/app/street/$id'
    | '/app/user/$id'
    | '/app/venue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/top': {
      id: '/app/top'
      path: '/top'
      fullPath: '/app/top'
      preLoaderRoute: typeof AppTopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/squad': {
      id: '/app/squad'
      path: '/squad'
      fullPath: '/app/squad'
      preLoaderRoute: typeof AppSquadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parties': {
      id: '/app/parties'
      path: '/parties'
      fullPath: '/app/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faze': {
      id: '/app/faze'
      path: '/faze'
      fullPath: '/app/faze'
      preLoaderRoute: typeof AppFazeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/venue/$id': {
      id: '/app/venue/$id'
      path: '/venue/$id'
      fullPath: '/app/venue/$id'
      preLoaderRoute: typeof AppVenueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user/$id': {
      id: '/app/user/$id'
      path: '/user/$id'
      fullPath: '/app/user/$id'
      preLoaderRoute: typeof AppUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/street/$id': {
      id: '/app/street/$id'
      path: '/street/$id'
      fullPath: '/app/street/$id'
      preLoaderRoute: typeof AppStreetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/city/$slug': {
      id: '/app/city/$slug'
      path: '/city/$slug'
      fullPath: '/app/city/$slug'
      preLoaderRoute: typeof AppCitySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFazeRoute: typeof AppFazeRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMapRoute: typeof AppMapRoute
  AppMeRoute: typeof AppMeRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppScanRoute: typeof AppScanRoute
  AppSquadRoute: typeof AppSquadRoute
  AppTopRoute: typeof AppTopRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppCitySlugRoute: typeof AppCitySlugRoute
  AppStreetIdRoute: typeof AppStreetIdRoute
  AppUserIdRoute: typeof AppUserIdRoute
  AppVenueIdRoute: typeof AppVenueIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFazeRoute: AppFazeRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppInboxRoute: AppInboxRoute,
  AppMapRoute: AppMapRoute,
  AppMeRoute: AppMeRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppScanRoute: AppScanRoute,
  AppSquadRoute: AppSquadRoute,
  AppTopRoute: AppTopRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppCitySlugRoute: AppCitySlugRoute,
  AppStreetIdRoute: AppStreetIdRoute,
  AppUserIdRoute: AppUserIdRoute,
  AppVenueIdRoute: AppVenueIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
